#Server config
server:
  port: ${SERVER_PORT:8222}

# Spring config
spring:
  application:
    name: gateway

# Gateway routes config
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED:true}

      routes:
        - id: crm-auth
          uri: lb://CRM
          predicates:
            - Path=/api/v1/auth/**

        - id: crm-trainee
          uri: lb://CRM
          predicates:
            - Path=/api/v1/trainee/**
            - Path=/api/v1/trainer/**
          filters:
            - AuthenticationFilter

        - id: crm-training
          uri: lb://CRM
          predicates:
            - Path=/api/v1/training/**
          filters:
            - AuthenticationFilter

        - id: trainer-hours-service
          uri: lb://TRAINER-HOURS-SERVICE
          predicates:
            - Path=/api/v1/workload/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}