services:

  discovery-service:
    build: ./services/discovery
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-service
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  gateway:
    container_name: gateway
    build:
      context: ./services/gateway
    environment:
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka/
      - CRM_URI=http://CRM
      - WORKLOAD_URI=http://TRAINER-HOURS-SERVICE
      - AUTH_URI=http://AUTH-SERVICE
      - HOSTNAME=gateway
    ports:
      - "8222:8222"
    depends_on:
      - discovery-service
    networks:
      - microservices-net

  auth-service:
    container_name: auth-service
    build:
      context: ./services/auth-service
    environment:
      - DATABASE_URL=jdbc:h2:mem:auth_db
      - DB_USERNAME=sa
      - DB_PASSWORD=password
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka/
      - ACTIVE_MQ=tcp://activemq:61616
      - HOSTNAME=auth-service
      - PROFILE=prod
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - activemq
    networks:
      - microservices-net


  workload-service:
    container_name: workload-service
    build:
      context: ./services/trainer-hours-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:workload
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka/
      - ACTIVE_MQ=tcp://activemq:61616
      - HOSTNAME=workload-service
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - DATABASE_URL_H2=jdbc:h2:mem:workload_db
      - DB_USERNAME_H2=sa
      - DB_PASSWORD_H2=password
      - ACTIVE_PROFILE=prod
    ports:
      - "8060:8060"
    depends_on:
      - discovery-service
    networks:
      - microservices-net


  crm-service:
    container_name: crm-service
    build:
      context: ./services/crm
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crm_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka/
      - ACTIVE_MQ=tcp://activemq:61616
      - HOSTNAME=crm-service
      - ACTIVE_PROFILE=prod
    depends_on:
      - auth-service
      - workload-service
      - discovery-service

    ports:
      - "8090:8090"
    networks:
      - microservices-net

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  activemq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - activemq-data:/var/lib/artemis-instance
    networks:
      - microservices-net

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - microservices-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres-data:
  pgadmin:
  activemq-data:
  mongo-data:
