  spring:
    application:
      name: discovery-service

  # Eureka server config
  eureka:
    server:
      enable-self-preservation: false
      evictionIntervalTimerInMs: 5000
    instance:
      hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    client:
      register-with-eureka: false
      fetch-registry: false

  # Server config
  server:
    port: 8761

  # Actuator config
  management:
    endpoints:
      web:
        base-path: /actuator
        exposure:
          include: health,info